import type { Bot } from 'mineflayer'
import { Vec3 } from 'vec3'
import type { EventEmitter } from 'node:events'
import type { EscapeDangerData, EscapeDangerParams, EstimatePathCostParams, FindNearestReachableParams, FindPathParams, FindSafeRouteParams, FollowPathParams, GoToBlockParams, GoToEntityData, GoToEntityParams, GoToPositionParams, IsReachableParams, NavigationExecutionData, NavigationGoal, NavigationNode, NavigationOptions, NavigationPath, PathCostEstimate, PathSearchResult, ReplanPathParams, ReturnHomeParams } from '../types/navigation.js'
import { NavigationError, NavigationErrorCode } from '../types/navigation.js'
import type { PathPlanner } from '../planner/PathPlanner.js'
import type { WalkabilityAnalyzer } from '../world/WalkabilityAnalyzer.js'
import type { PathValidator } from '../path/PathValidator.js'
import type { PathOptimizer } from '../path/PathOptimizer.js'
import type { PathExecutor } from '../path/PathExecutor.js'
import type { NavigationCostModel } from '../cost/NavigationCostModel.js'
import type { NavigationLock } from './NavigationLock.js'
import type { NavigationLogger } from './MovementFacade.js'
import { asGoal, distance3D, nodePosition } from '../utils/math.js'
import { combineSignals, throwIfAborted } from '../utils/async.js'
export class NavigationService {
  constructor(private readonly bot:Bot,private readonly planner:PathPlanner,private readonly analyzer:WalkabilityAnalyzer,private readonly validator:PathValidator,private readonly optimizer:PathOptimizer,private readonly executor:PathExecutor,private readonly costs:NavigationCostModel,private readonly lock:NavigationLock,private readonly logger:NavigationLogger,private readonly events:EventEmitter,private readonly home?:Vec3){}
  async findPath(params:FindPathParams,signal?:AbortSignal):Promise<PathSearchResult>{const start=this.resolveStart(),goal=asGoal(params.target);this.events.emit('navigation:search:start',{event:'navigation:search:start',timestamp:Date.now(),start:nodePosition(start),goal:goal.position});const result=await this.planner.findPath(start,goal,params,signal);if(result.success&&result.path&&params.optimizePath!==false)result.path=this.optimizer.optimize(result.path);this.events.emit(result.success?'navigation:path:found':'navigation:path:failed',{event:result.success?'navigation:path:found':'navigation:path:failed',timestamp:Date.now(),expandedNodes:result.expandedNodes,cost:result.path?.cost,status:result.status});this.logger.info(`[NAV][findPath] ${result.status}`,{expandedNodes:result.expandedNodes,cost:result.path?.cost,durationMs:result.durationMs});return result}
  async followPath(params:FollowPathParams,signal?:AbortSignal):Promise<NavigationExecutionData>{const lease=await this.lock.acquire(`followPath:${Date.now()}`,'normal','wait',signal),combined=combineSignals(signal,lease.signal);try{await this.executor.execute(params.path,{waypointTolerance:params.waypointTolerance,maxSafeDrop:3},combined);return this.executionData(params.path,0)}finally{lease.release()}}
  async goToPosition(params:GoToPositionParams,signal?:AbortSignal):Promise<NavigationExecutionData>{const priority=params.priority??'normal',mode=priority==='emergency'?'preempt':'wait',lease=await this.lock.acquire(`goToPosition:${Date.now()}`,priority,mode,signal),combined=combineSignals(signal,lease.signal);try{return await this.navigateWithReplans({position:new Vec3(params.x,params.y,params.z),tolerance:params.tolerance??0.75},params,combined)}finally{lease.release()}}
  async goToBlock(params:GoToBlockParams,signal?:AbortSignal):Promise<NavigationExecutionData>{const target=params.block.position.clone(),tolerance=Math.max(1,Math.min(params.interactionDistance??4.5,4.5)),lease=await this.lock.acquire(`goToBlock:${Date.now()}`,'normal','wait',signal),combined=combineSignals(signal,lease.signal);try{return await this.navigateWithReplans({position:target,tolerance,verticalTolerance:3},params,combined)}finally{lease.release()}}
  async goToEntity(params:GoToEntityParams,signal?:AbortSignal):Promise<GoToEntityData>{const lease=await this.lock.acquire(`goToEntity:${Date.now()}`,'normal','wait',signal),combined=combineSignals(signal,lease.signal);let replans=0,lastPath:NavigationPath|undefined;try{while(true){throwIfAborted(combined);const botPos=this.bot.entity.position;if(distance3D(botPos,params.entity.position)<=(params.distance??3)){if(!lastPath){lastPath=await this.requirePath({target:{position:params.entity.position.clone(),tolerance:params.distance??3},...params},combined)}return{...this.executionData(lastPath,replans),targetPosition:params.entity.position.clone()}}if(replans>(params.maxReplans??12))throw new NavigationError(NavigationErrorCode.REPLAN_LIMIT,'Entity navigation exceeded replan limit');const snapshot=params.entity.position.clone(),path=await this.requirePath({target:{position:snapshot,tolerance:params.distance??3},...params},combined);lastPath=path;const chunkSize=6,chunk:NavigationPath={...path,waypoints:path.waypoints.slice(0,chunkSize),length:Math.min(chunkSize,path.waypoints.length)};await this.executor.execute(chunk,params,combined);if(distance3D(snapshot,params.entity.position)>(params.repathDistance??2)){replans++;this.events.emit('navigation:replan',{event:'navigation:replan',timestamp:Date.now(),reason:'dynamic_target',replans});continue}if(path.waypoints.length>chunkSize){replans++;continue}}}finally{lease.release()}}
  async replanPath(params:ReplanPathParams,signal?:AbortSignal):Promise<PathSearchResult>{this.events.emit('navigation:replan',{event:'navigation:replan',timestamp:Date.now(),reason:'explicit'});return this.findPath(params,signal)}
  async findSafeRoute(params:FindSafeRouteParams,signal?:AbortSignal):Promise<PathSearchResult>{return this.findPath({...params,profile:'safe',avoidHazards:true,allowSafeDrops:params.allowSafeDrops??true},signal)}
  async isReachable(params:IsReachableParams,signal?:AbortSignal):Promise<{reachable:boolean;cost?:number;pathLength?:number}>{const r=await this.findPath({...params,optimizePath:false},signal),cost=r.path?.cost;return{reachable:r.success&&(params.maxCost===undefined||Boolean(cost!==undefined&&cost<=params.maxCost)),cost,pathLength:r.path?.length}}
  async estimatePathCost(params:EstimatePathCostParams,signal?:AbortSignal):Promise<PathCostEstimate>{const r=await this.findPath({...params,optimizePath:false},signal);if(!r.success||!r.path)return{reachable:false};return{reachable:true,cost:r.path.cost,estimatedDistance:this.pathDistance(r.path),estimatedTravelTime:r.path.estimatedTravelTime,hazardScore:r.path.hazardScore}}
  async findNearestReachable(params:FindNearestReachableParams,signal?:AbortSignal):Promise<{target:NavigationGoal;path:NavigationPath}|undefined>{const origin=this.bot.entity.position,targets=params.targets.map(t=>asGoal(t)).sort((a,b)=>distance3D(origin,a.position)-distance3D(origin,b.position)).slice(0,params.maxCandidates??16);let best:{target:NavigationGoal;path:NavigationPath}|undefined;for(const target of targets){throwIfAborted(signal);const r=await this.findPath({...params,target,optimizePath:false},signal);if(r.success&&r.path&&(!best||r.path.cost<best.path.cost))best={target,path:r.path}}return best}
  async escapeDanger(params:EscapeDangerParams,signal?:AbortSignal):Promise<EscapeDangerData>{if(params.dangerPositions.length===0)throw new NavigationError(NavigationErrorCode.INVALID_GOAL,'escapeDanger requires at least one danger position');const lease=await this.lock.acquire(`escapeDanger:${Date.now()}`,'emergency','preempt',signal),combined=combineSignals(signal,lease.signal);try{const origin=this.bot.entity.position.clone(),radius=params.searchRadius??24,count=Math.max(8,params.candidateCount??16),min=params.minimumDistance??12,candidates:Vec3[]=[];for(let i=0;i<count;i++){const a=Math.PI*2*i/count;candidates.push(new Vec3(origin.x+Math.cos(a)*radius,origin.y,origin.z+Math.sin(a)*radius))}let best:{path:NavigationPath;pos:Vec3;dangerDistance:number;score:number}|undefined;for(const pos of candidates){throwIfAborted(combined);const dd=Math.min(...params.dangerPositions.map(d=>distance3D(pos,d)));if(dd<min)continue;const r=await this.findSafeRoute({...params,target:{position:pos,tolerance:2},maxDistance:Math.max(radius*2,params.maxDistance??0)},combined);if(!r.success||!r.path)continue;const score=dd*5-r.path.cost-r.path.hazardScore*10;if(!best||score>best.score)best={path:r.path,pos,dangerDistance:dd,score}}if(!best)throw new NavigationError(NavigationErrorCode.PATH_NOT_FOUND,'No safe escape route found');await this.executor.execute(best.path,{...params,profile:'safe',avoidHazards:true},combined);return{...this.executionData(best.path,0),safePosition:best.pos,minimumDangerDistance:best.dangerDistance}}finally{lease.release()}}
  async returnHome(params:ReturnHomeParams={},signal?:AbortSignal):Promise<NavigationExecutionData>{const home=params.home??this.home;if(!home)throw new NavigationError(NavigationErrorCode.INVALID_GOAL,'No home position configured');const lease=await this.lock.acquire(`returnHome:${Date.now()}`,'normal','wait',signal),combined=combineSignals(signal,lease.signal);try{return await this.navigateWithReplans({position:home,tolerance:1},{...params,profile:'safe',avoidHazards:true},combined)}finally{lease.release()}}
  private async navigateWithReplans(goal:NavigationGoal,options:NavigationOptions&{replan?:boolean;maxReplans?:number},signal?:AbortSignal):Promise<NavigationExecutionData>{let replans=0,path:NavigationPath|undefined;for(;;){throwIfAborted(signal);path=await this.requirePath({...options,target:goal},signal);try{await this.executor.execute(path,options,signal);return this.executionData(path,replans)}catch(raw){const e=raw instanceof NavigationError?raw:new NavigationError(NavigationErrorCode.MOVEMENT_FAILED,raw instanceof Error?raw.message:String(raw));if(options.replan===false||![NavigationErrorCode.PATH_BLOCKED,NavigationErrorCode.MOVEMENT_FAILED].includes(e.code))throw e;replans++;if(replans>(options.maxReplans??4))throw new NavigationError(NavigationErrorCode.REPLAN_LIMIT,`Replan limit reached (${replans})`);this.events.emit('navigation:replan',{event:'navigation:replan',timestamp:Date.now(),reason:e.code,replans})}}}
  private async requirePath(params:FindPathParams,signal?:AbortSignal):Promise<NavigationPath>{const r=await this.findPath(params,signal);if(!r.success||!r.path){const code=r.status==='search_limit'?NavigationErrorCode.SEARCH_LIMIT:r.status==='timeout'?NavigationErrorCode.TIMEOUT:r.status==='unknown_world'?NavigationErrorCode.CHUNK_UNLOADED:NavigationErrorCode.PATH_NOT_FOUND;throw new NavigationError(code,r.reason??'Path not found',{expandedNodes:r.expandedNodes})}return r.path}
  private resolveStart():NavigationNode{if(!this.bot.entity)throw new NavigationError(NavigationErrorCode.INVALID_START,'Bot entity is not ready');const p=this.bot.entity.position,x=Math.floor(p.x),z=Math.floor(p.z),s=this.analyzer.nearestStandable(x,z,p.y,p.y-1.5,p.y+1.5,{allowWater:true,allowClimbing:true,avoidHazards:false});if(s?.valid&&s.feetY!==undefined)return{x,y:s.feetY,z,mode:s.mode,metadata:{blockBelow:s.blockBelow,water:s.water,climbable:s.climbable,hazard:s.hazard}};const direct=this.analyzer.standability(x,p.y,z,{allowWater:true,allowClimbing:true,avoidHazards:false});if(direct.valid)return{x,y:direct.feetY??p.y,z,mode:direct.mode,metadata:{blockBelow:direct.blockBelow,water:direct.water,climbable:direct.climbable,hazard:direct.hazard}};throw new NavigationError(NavigationErrorCode.INVALID_START,'Current bot position is not a valid navigation node')}
  private executionData(path:NavigationPath,replans:number):NavigationExecutionData{const finalPosition=this.bot.entity.position.clone();return{path,replans,finalPosition,finalDistance:distance3D(finalPosition,path.goal.position)}}
  private pathDistance(path:NavigationPath):number{let total=0;for(let i=1;i<path.nodes.length;i++)total+=distance3D(path.nodes[i-1]!,path.nodes[i]!);return total}
}
